---
- name: Rollback nirvana-frontend to my server
  hosts: frontservers
  vars:
    ansistrano_deploy_to: /mnt/www/yt_wap/
  user: deploy
  roles:
    - { role: carlosbuenosvinos.ansistrano-rollback }
  tasks:
    - name: restart nginx after rollback
      shell: sudo service nginx restart
